### ISSUE TITLE
System-wide installation of ROL results in permission issues

### ISSUE THREAD

**Issue by grondman** [robotcaresystems/RoboticsLanguage#74]
After doing a system-wide installation of ROL with
```
sudo pip install RoboticsLanguage
```
a non-root user cannot create an output template:
```
$ rol --create-output-template mytemplate
2019-05-01 11:59:11 Ivo-ThinkPad root[21462] ERROR File system error: Operation not permitted
```
If the user tries it with sudo, the template is created in his/her own home directory:
```
$ sudo rol --create-output-template mytemplate
[sudo] password for ivogrondman: 
Created Outputs plugin "Mytemplate" in folder /home/ivogrondman/.rol/plugins//Outputs/Mytemplate
```
but the files created are owned by the root user.

A system-wide installation should still allow individual users to create self-owned templates in their own home directories.

**Comment by gadlopes** [comment]
Great find, thanks! I will take a look at this asap.

**Comment by gadlopes** [comment]
Found the problem:

https://github.com/robotcaresystems/RoboticsLanguage/blob/1b1d218b7e284668db94c3fcad914da429093375/RoboticsLanguage/Tools/Templates.py#L272

https://github.com/robotcaresystems/RoboticsLanguage/blob/1b1d218b7e284668db94c3fcad914da429093375/RoboticsLanguage/Base/Utilities.py#L682

Fix soon

**Comment by gadlopes** [comment]
check https://github.com/robotcaresystems/RoboticsLanguage/tree/feature/issue/74
