### ISSUE TITLE
Utilities.logger vs Utilities.logging

### ISSUE THREAD

**Issue by grondman** [robotcaresystems/RoboticsLanguage#75]
Throughout the code, logging is done by calls to both a Logger object (Utilities.logger) and by calling module-level functions (e.g. Utilities.logging.error). The file `RoboticsLanguage/Outputs/RosCpp/Output.py` even uses both, but it's unclear why in one case the object is used and in another case the module-level function. Perhaps this should be cleaned up at some point?

**Comment by gadlopes** [comment]
Great catch, thanks!!
I think I just forgot to use the `Utilities.logger` function. Changed all to `Utilities.logger` in a new branch. Testing now.
